### ISSUE TITLE
Set up a working prototype

### ISSUE THREAD

**Issue by threezool** [DigitalZoolutions/Savely-Prototype#1]
Set up a project using Xamarin to develop a working prototype.

Goals:
- Get a feel for the UI
- Work out the navigation
- Get feedback and implement changes 

Milestones:
- [x] Create a Xamarin project #2 
- [x] Create a page structure for navigation #3 
- [x] Populate the pages with content
- [x] Create mockup endpoints
- [x] Add style and design to the pages
- [ ] internal testing
